//数据定义
CREATE TABLE T(
    T# CHAR(4) NOT NULL,
    TNAME CHAR(12) NOT NULL,
    TITLE CHAR(10),
    PRIMARY KEY(T#));

CREATE TABLE C(
    C# CHAR(4) NOT NULL,
    CNAME CHAR(8) NOT NULL,
    T# CHAR(4),
    PRIMARY KEY(C#),
    FOREIGN KEY(T#) REFERENCES T(T#));

CREATE TABLE S(
    S# CHAR(4) NOT NULL,
    SNAME CHAR(12) NOT NULL,
    AGE SMALLINT,
    SEX CHAR(1),
    PRIMARY KEY(S#));

CREATE TABLE SC(
    S# CHAR(4);
    C# CHAR(4);
    SCORE SMALLINT,
    PRIMARY KEY(S#,C#),
    FOREIGN KEY(S#) REFERENCES S(S#),
    FOREIGN KEY(C#) REFERENCES C(C#));

//DROP TABLE S;
//
ALTER TABLE S ADD AGE CHAR(4);
ALTER TABLE S DROP AGE;
ALTER TABLE S MODIFY AGE CHAR(6);

//数据查询
SELECT S.S#,SNAME FROM S,SC WHERE S.S# = SC.S# AND C# = 'C2';
SELECT S#,SNAME FROM S WHERE S# IN(SELECT S# FROM SC WHERE C# = 'C2');
SELECT S#,NAME FROM S WHERE 'C2' IN (SELECT S# FROM SC WHERE S# = S.S#);
SELECT S#,NAME FROM S WHERE EXIST (SELECT * FROM SC WHERE SC.S# = S.S# AND C# = 'C2');
SELECT X.S# WHERE SC AS X, SC AS Y WHERE X.S# = Y.S# AND C.C# = 'C2' AND Y.C# = 'C4';
SELECT DISTINCT S# FROM SC AS X WHERE NOT EXISTS (SELECT * FROM SC AS Y WHERE Y.S# = 'S3' AND NOT EXISTS(SELECT * FROM SC AS Z WHERE Z.S# = X.S# AND Z.C# = Y.C#))

SELECT T#,C.C#,COUNT(S#) FROM C,SC WHERE C.C# = SC.C# GROUP BY T#,C.C# HAVING COUNT(*) > 50 ORDER BY 3,T#,C.C#;
SELECT COUNT(S#) + 100,COUNT(*),SUM(S#),AVG(S#),MAX(S#),MIN(S#) FROM S,SC WHERE S.S# = SC.S# AND C# = 'C2';

(SELECT S.S#,SNAME FROM S,SC WHERE S.S# = SC.S# AND C# = 'C2') UNION (INTERSECT EXCEPT) [ALL]
(SELECT S.S#,SNAME FROM S,SC WHERE S.S# = SC.S# AND C# = 'C2')
//数据更新
INSERT INTO S[(S#)] VALUES('1','1','1'),('1','1','1');
INSERT INTO S[(S#)] SELECT S.S#,SNAME FROM S,SC WHERE S.S# = SC.S# AND C# = 'C2';
INSERT INTO S[(S#)] TABLE S;
DELETE FROM S [WHERE]
UPDATE C SET CNAME = 'DB' WHERE C# = 'C5';

//索引
CREATE [UNIQUE] INDEX S#_INDEX ON S(S#)
DROP INDEX S#_INDEX

//视图
CREATE VIEW STU_S (S#,SNAME,CNAME,SCORE) WITH CHECK OPTION
AS SELECT S.S#,SNAME,CNAME,SCORE FROM S,SC,C WHERE S.S# = SC.S# AND SC.C# = C.C#;

DROP VIEW STU_S;